name: CodeQL Migration Automation

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  migrate-codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'  # Enables dependency caching

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migration Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e  # Exit if any command fails
          python migrator.py || { echo "Migration failed. Check logs."; exit 1; }

      - name: Notify on Failure
        if: failure()
        run: echo "CodeQL migration failed. Check workflow logs for details."
